### ISSUE TITLE
Can Bayeux help leverage TFP for Apple Silicon GPU?

### ISSUE THREAD

**Issue by zwelitunyiswa** [jax-ml/bayeux#30]
I am on a M1 Ultra with the silicon GPU. Given that Tensorflow has Apple Silicon GPU support. Can I leverage that via Bayeux? I installed Tensorflow + the TensorFlow Metal library (and Tensorflow sees the GPU) but I cannot figure out how to tell Bayeux to tell Tensorflow-Probability to use Tensorflow instead of JAX, and thus the GPU.

![Screenshot 2024-02-21 at 12 51 55 PM](https://github.com/jax-ml/bayeux/assets/32966743/d322faac-4d07-4a77-b57f-eabc66195dae)

**Comment by ColCarroll** [comment]
Bayeux is JAX only! There's a _chance_ you could use [jx2tf](https://www.tensorflow.org/guide/jax2tf) to convert the function, but I've never tried this. 

Note that at that point, you'd be doing something like Python -> PyTensor -> JAX -> TensorFlow.

**Comment by zwelitunyiswa** [comment]
Ah! Ok. I get it. I might try that just to see if I can get it to work! Thank you.

**Comment by ColCarroll** [comment]
Good luck! Let me know how it goes.
