### ISSUE TITLE
Arviz updated to Scipy 1.13

### ISSUE THREAD

**Issue by danieltomasz** [jax-ml/bayeux#39]
Arviz fixed  Scipy dependency in the new release, bayeux can unpin it.
https://github.com/arviz-devs/arviz/pull/2332

**Comment by danieltomasz** [comment]
Ok, pinning  is due to arviz dropping Python 3.9

**Comment by ColCarroll** [comment]
thanks! i'll unpin early next week (unless you need a pip release in the meantime -- not a big deal!)

**Comment by danieltomasz** [comment]
I could wait 🙂
Just you need to know that latest 'arviz' has ' python_requires=">=3.10'even if this is not mentioned in release notes (since your latest release was enabling again Python 3.9)
